- name: install the maven package 
  ansible.builtin.import_role:
    name: common
    tasks_from: maven-setup

- name: setup the application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install the dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: Renaming the file
  ansible.builtin.command: "mv target/shipping-1.0.jar shipping.jar"
  args:
    chdir: /app

- name: Loading the schema
  ansible.builtin.import_role:
    name: common
    tasks_from: load-mysql-schema

- name: enabling and restarting the service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup
  